name = "EasyHybrid"
uuid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"
authors = ["MR"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
